export const NOTE_CREATE = 'NOTE/NOTE_CREATE'
export const NOTE_REMOVE = 'NOTE/NOTE_REMOVE'
export const NOTE_CHECKED = 'NOTE/NOTE_CHECKED'

export const NOTE_CHANGE_IMPORTANT = 'NOTE/CHANGE_IMPORTANT'
export const NOTE_CHANGE_STATUS = 'NOTE/CHANGE_STUTUS'
export const NOTE_CHANGE_TAGS = 'NOTE/CHANGE_TAGS'
export const NOTE_CHANGE_REMINDER = 'NOTE/CHANGE_REMINDER'
export const NOTE_CHANGE_INIT = 'NOTE/CHANGE_INIT'

export const NOTE_SELECT_GROUP = 'NOTE/SELECT_GROUP'
export const NOTE_SELECT_NOTE = 'NOTE/SELECT_NOTE'
export const NOTE_VIEW_NOTE = 'NOTE/VIEW_NOTE'
